### ISSUE TITLE
GameHUDManager

### ISSUE THREAD

**Issue by thomabel** [Resourceful-Rails-Team/resourceful-rails-game#58]
With the `RemoveNode()` method changed `GameHUDManager` needs to be changed to agreed with it on line 278.

**Comment by ChristianNoelSchmid** [comment]
Just in case @Dnawrkshp, I wanted to give some input - you've probably already seen this before but I spent 10 hours trying to figure it out in the past, and it was frustrating lol.

When you pass index `i` into the `item.OnTrackSelected => (track)` make sure you create a local variable assigned the same value as `i`, and use that in the invoked method instead. Otherwise `i` will be treated by reference rather than value, and it will make the function all messed up.
